export default {
  LOAD_GLOBAL: 'LOAD_GLOBAL',
  LOAD_GLOBAL_ERROR: 'LOAD_GLOBAL_ERROR',
  LOAD_COUNTRY: 'LOAD_COUNTRY',
  LOAD_COUNTRY_HISTORY: 'LOAD_COUNTRY_HISTORY',
  LOAD_VACCINES_MAP: 'LOAD_VACCINES_MAP',
  LOAD_VACCINES_BY_COUNTRY: 'LOAD_VACCINES_BY_COUNTRY',
  LOAD_VACCINES_BY_CONTINENT: 'LOAD_VACCINES_BY_CONTINENT',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  ADD_FAV: 'ADD_FAV',
  DELETE_FAV: 'DELETE_FAV'
};
